Traceback (most recent call last):
  File "train.py", line 123, in <module>
    main(args,42)
  File "train.py", line 70, in main
    trainer = Trainer(
  File "/home/tbertrand/anaconda3/envs/ULM_landmark/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 38, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/tbertrand/anaconda3/envs/ULM_landmark/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 426, in __init__
    gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
  File "/home/tbertrand/anaconda3/envs/ULM_landmark/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1543, in _parse_devices
    gpu_ids = device_parser.parse_gpu_ids(gpus)
  File "/home/tbertrand/anaconda3/envs/ULM_landmark/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 89, in parse_gpu_ids
    return _sanitize_gpu_ids(gpus)
  File "/home/tbertrand/anaconda3/envs/ULM_landmark/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 151, in _sanitize_gpu_ids
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0]
 But your machine only has: []